### ISSUE TITLE
Maintain a set of Traits

### ISSUE THREAD

**Issue by joegluntz** [engooyen/majel#13]
It'd be useful if users could add & remove traits, kept track in a list like the momentum & threat pool.

Traits could just have a "name" and a "tag". Both could be free-form and the tag could be optional - used as shorthand to pin the Trait to a player, NPC, ship, etc.

**Comment by engooyen** [comment]
Hi @joegluntz 

Sorry of for the late response. This is a great idea! Here are the commands I'm thinking of:

!trait set [name (required)] [tag (required)] - Add / set a tag to current named trait
!trait set [name (required)] [tag (required)] [value (optional)] - Add / set a tag to current named trait with a value. Could be a number in case you to track the number of items in an inventory or some text like a message on a data pad.
!trait unset [name (required)] [tag (optional)] - Removes a specific tag from the named trait.
!trait unset [name (required)] - Removes remove all traits under the named trait.

Let me know what you think. If there's another name you can think of to make it clear that each player/npc/ship/enemy can have a collection of traits, let me know as well.

**Comment by engooyen** [comment]
@kkotenko What do you think about this feature?

**Comment by kkotenko** [comment]
@engooyen Looks good to me

**Comment by engooyen** [comment]
Simplified the commands to:

`!trait` - List all containers and their traits.
`!trait set [container] [trait] [value]` - Set a value to a trait within a container.
`!trait del [container] [trait]` - Delete a key within a container.
`!trait del [container]` - Delete a container.
