### ISSUE TITLE
More details on developer setup

### ISSUE THREAD

**Issue by kkotenko** [engooyen/majel#18]
As is now, I am not sure how to test my changes. Is there any way you could link to a more comprehensive tutorial? Could I just have it run on localhost? How do I invite my local Majel version to a server to actually test the commands I implement?

**Comment by engooyen** [comment]
Hi @kkotenko. I've merged your changes and thank you! I've updated the Developer Setup section. Let me know if you are able to follow these steps. If you can improve the developer experience, please update the readme. If help is needed, we can setup a session this weekend if needed.

**Comment by kkotenko** [comment]
Worked like a charm, thanks!
