### ISSUE TITLE
Add "momentum" role to allow other users than server owner to manage momentum

### ISSUE THREAD

**Issue by kkotenko** [engooyen/majel#37]
In my use case, I am both owner and GM of our server where we are the only gaming group. It is an additional task for me to track momentum and I would like to delegate this to another player. 

I propose a new role "momentum" which allows users to manage the momentum pool even if they are not the server owner. 
Majel would then check for "user is owner or user has group 'momentum'". The role could be manually assigned. 

A bonus would be if Majel could allow the owner to assign this role to other users, but that is really a low-priority task (since a server owner can assign roles at will anyway)

**Comment by engooyen** [comment]
I'm wondering if it's necessary at all with the original implementation to only restrict to server owners to manage the pool. My original thinking was to prevent any accidents by player misuse. So far players have been responsible and trusted by the GM.

**Comment by kkotenko** [comment]
Agreed. What about threat management and resetting the pool? My personal approach would be to trust the users here as well.

**Comment by engooyen** [comment]
I think we should lift the restriction for all aspects. We should promote a culture of trust between the GM and players.
