### ISSUE TITLE
Migrate Majel to Slash Commands

### ISSUE THREAD

**Issue by kkotenko** [engooyen/majel#49]
Discord recently introduced the ability to use [Slash Commands](https://discord.com/developers/docs/interactions/slash-commands). While it seems they require a bit more setup upfront, they

* are more user-friendly (user can [see all the command options on typing](https://discord.com/assets/5002338abeaf8532983a1be594a10683.png))
* new commands seem to be somewhat nicer to implement

To be evaluated: 

* How hard is the setup, really?
* How do Slash Commands behave if multiple bots try to register the same Slash Command (eg /version or /2d20)?
* Would switching to Slash Commands require changing syntax (e.g. `/2d20` becomes `/roll 2 20` because it's not clear to me if it is possible to include (semantically) parameters as part of the command)

**Comment by engooyen** [comment]
In the works.
