### ISSUE TITLE
/support doesn't seem to be working for me

### ISSUE THREAD

**Issue by omgthegreenranger** [engooyen/majel#50]
Not sure if I'm using it correctly or not. I can generate an alien, technobabble works, rolling dice works, but /support doesn't seem to work. I can't get a list or generate a random crew, but I can get the help message.

Do I need to include a locally-hosted server for that to work?

**Comment by engooyen** [comment]
You don't have to host the bot. I'll look into this issue and will get back to you.

**Comment by engooyen** [comment]
Support is now working again. Thanks for reporting this issue to us!
