### ISSUE TITLE
Add: a way to change command prefix to something other than '!'

### ISSUE THREAD

**Issue by tenwen** [engooyen/majel#6]

**Comment by engooyen** [comment]
I'll add '/' as a prefix as well.

**Comment by engooyen** [comment]
Added '/' support. Commands can now be triggered with ! or /.

**Comment by engooyen** [comment]
I'm hosting another Majel bot that exclusively uses the "/" please add this [bot](https://discordapp.com/api/oauth2/authorize?client_id=729181873024139294&permissions=51200&scope=bot). The current bot will now use only the "!" prefix.
