### ISSUE TITLE
Request adding number of dice to roll in /d20 

### ISSUE THREAD

**Issue by BobScheid** [engooyen/majel#65]
Instead of having the roll set up in one command and then having to go back to select 2 dice from the dropdown, it would be great to enter the number of dice to roll within the template in the /d20 command. If implemented, I also request a default value of 2 dice to roll
![d20_rolls](https://user-images.githubusercontent.com/113315009/189551484-aa9ddbf6-46af-4ddb-bc3a-d4e34ce532bb.png)

**Comment by j-simmons-phd** [comment]
+1

**Comment by engooyen** [comment]
I'll revert the d20 roll back to it's original behavior where you specify all the parameters and perform the roll on the spot. No more of this 2-step process.

**Comment by j-simmons-phd** [comment]
Thanks!

**Comment by BobScheid** [comment]
Yes, thanks so much! Much appreciated
