### ISSUE TITLE
majel shows up in new servers with zero commands

### ISSUE THREAD

**Issue by magicatherine** [engooyen/majel#71]
majel isn't working when i've tried adding her to new servers, for some reason the bot shows up with no commands listed, so obviously none of our commands to her work at all. i have an old STA server that's had majel for a long time, and she works just fine there, it's only a problem with adding her to a new server. also it's not a permissions problem as far as i can tell, i've given her admin power and that hasn't changed anything. thanks!

**Comment by engooyen** [comment]
Try now

**Comment by magicatherine** [comment]
we're still having the same issue :( this is what it looks like on her manage integrations page:

<img width="715" alt="Screenshot 2023-10-23 at 11 49 29 AM" src="https://github.com/engooyen/majel/assets/91255904/6cbec43d-3eaa-4046-8b00-d86896f2c49e">

**Comment by magicatherine** [comment]
OMG she JUST started working! thank you sm!!!!!
