### ISSUE TITLE
Other 2d20 systems

### ISSUE THREAD

**Issue by WinkYahoo** [engooyen/majel#9]
Not submitting a problem it works like a dream, just wondered if there was a older version without the Star Trek insignia available to invite, I'm planning to use it for Fallout. Thanks by the way, we can't play in person at the moment obviously so this is a life saver.

**Comment by engooyen** [comment]
I'll look into a solution for you and get back to you this week, hopefully.

**Comment by engooyen** [comment]
Note to self. Refactor the code base to be configurable and game agnostic.

**Comment by engooyen** [comment]
Bot is available to add here: https://discord.com/oauth2/authorize?client_id=831001838971125760&permissions=51200&scope=bot
